-- MySQL数据库初始化脚本

-- 创建数据库（如果不存在）
CREATE DATABASE IF NOT EXISTS chat_bi CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE chat_bi;

-- 设置会话变量
SET sql_mode = 'NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES';

-- 执行航班数据DDL
-- 注意：由于原始DDL使用Oracle语法，需要进行转换
-- 这里我们直接执行转换后的MySQL语法

-- 航班信息表
CREATE TABLE `DW_OPT_FLIGHT` (
  `ID` BIGINT NOT NULL,
  `PID` BIGINT,
  `OPT_FP_FLID` NUMERIC(12,0),
  `OPT_FP_GUFI` VARCHAR(40),
  `OPT_AC_AIRLINE` VARCHAR(3),
  `OPT_FP_FLTNO` VARCHAR(12),
  `OPT_FP_FLTNUM` VARCHAR(12),
  `OPT_FP_DEP_AP` VARCHAR(3),
  `OPT_FP_ARR_AP` VARCHAR(3),
  `OPT_FP_ROUTE` VARCHAR(25),
  `OPT_FP_SODT` DATETIME(6),
  `OPT_FP_EXECUTE_DATE` DATE,
  `OPT_FP_EXECUTE_TIME` TIME(6),
  `OPT_FP_MVIN` VARCHAR(1),
  `OPT_FP_SOBT` DATETIME(6),
  `OPT_FP_SIBT` DATETIME(6),
  `OPT_FS_CTOT` DATETIME(6),
  `OPT_FS_ELDT` DATETIME(6),
  `OPT_FS_ATOT` DATETIME(6),
  `OPT_FS_ALDT` DATETIME(6),
  `OPT_FS_PREAOBT` DATETIME(6),
  `OPT_FS_NEXTALDT` DATETIME(6),
  `OPT_FP_FLTY` VARCHAR(1),
  `OPT_FP_FLIN` VARCHAR(1),
  `OPT_FP_AIRCRAFT_TYPE` VARCHAR(3),
  `OPT_FP_REG_NUMBER` VARCHAR(10),
  `OPT_FP_TAOP` VARCHAR(3),
  `OPT_FP_TAFL` VARCHAR(12),
  `OPT_FP_TAID` NUMERIC(12,0),
  `SCT_STC_TERMINAL` VARCHAR(5),
  `SCT_STC_TERMINAL_NAME_CHN` VARCHAR(20),
  `OPT_AC_MAX_SEAT_NUMBER` NUMERIC(3,0),
  `OPT_AC_AIRLINE_MAIN` VARCHAR(3),
  `OPT_FP_FLTNUM_MAIN` VARCHAR(12),
  `OPT_FRA_DEP_STAND` VARCHAR(8),
  `OPT_FRA_CHECK_IN_DESK` NUMERIC(9,0),
  `OPT_FL_SCNL` DATETIME(6),
  `OPT_FS_REMARK` VARCHAR(160),
  `OPT_FGS_ASBT` DATETIME(6),
  `OPT_FGS_LACL` DATETIME(6),
  `OPT_FS_ETA` DATETIME(6),
  `OPT_FP_APPT` DATETIME(6),
  `OPT_FP_ASRT` DATETIME(6),
  `OPT_FS_STARTTIME` DATETIME(6),
  `OPT_FS_FHAG` NUMERIC(9,0),
  `OPT_FS_MHAG` NUMERIC(9,0),
  `OPT_FS_VIPP` NUMERIC(3,0),
  `OPT_FP_VIPR` NUMERIC(1,0),
  `OPT_FP_FDIV` VARCHAR(100),
  `OPT_FP_DDES` VARCHAR(3),
  `OPT_FP_DDIR` VARCHAR(4),
  `OPT_FL_ALTREASON` VARCHAR(30),
  `OPT_FL_REID` VARCHAR(1),
  `OPT_FS_FLAB` VARCHAR(90),
  `OPT_FS_ARES` VARCHAR(1),
  `OPT_PCS_LUGGAGE_SUM` NUMERIC(3,0),
  `OPT_PCS_LUGGAGE_WEIGHT` NUMERIC(9,2),
  `OPT_PCS_PASSENGER_SUM` NUMERIC(3,0),
  `ODS_ID` BIGINT,
  `CREATED_TIME` TIMESTAMP(6),
  `UPDATED_TIME` TIMESTAMP(6),
  `CREATED_BY` VARCHAR(32),
  `UPDATED_BY` VARCHAR(32),
  `DELETE_FLAG` NUMERIC(1,0),
  `OPT_FP_FLTID` VARCHAR(100),
  `OPT_FS_STATUS` VARCHAR(50),
  `OPT_FS_STATUS_HX` VARCHAR(50),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='航班信息表';

-- 航班信息子表-登机桥表
CREATE TABLE `DW_OPT_FLIGHT_ABTM` (
  `ID` BIGINT NOT NULL,
  `PID` BIGINT,
  `OPT_FS_ASNO` NUMERIC(2,0),
  `OPT_FS_ABDG` VARCHAR(8),
  `OPT_FS_ABOP` VARCHAR(1),
  `OPT_FS_AOTM` DATETIME(6),
  `ODS_ID` BIGINT,
  `CREATED_TIME` TIMESTAMP(6),
  `UPDATED_TIME` TIMESTAMP(6),
  `CREATED_BY` VARCHAR(32),
  `UPDATED_BY` VARCHAR(32),
  `DELETE_FLAG` NUMERIC(1,0),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='航班信息子表-登机桥表';

-- 航班信息子表-行李传送带表
CREATE TABLE `DW_OPT_FLIGHT_CHDT` (
  `ID` BIGINT NOT NULL,
  `PID` BIGINT,
  `OPT_FS_CHNO` NUMERIC(1,0),
  `OPT_FS_CHUT` VARCHAR(8),
  `OPT_FS_CCLS` VARCHAR(1),
  `OPT_FS_PCBT` DATETIME(6),
  `OPT_FS_PCET` DATETIME(6),
  `OPT_FS_CBTM` DATETIME(6),
  `OPT_FS_CETM` DATETIME(6),
  `OPT_FS_CTYP` VARCHAR(1),
  `ODS_ID` BIGINT,
  `CREATED_TIME` TIMESTAMP(6),
  `UPDATED_TIME` TIMESTAMP(6),
  `CREATED_BY` VARCHAR(32),
  `UPDATED_BY` VARCHAR(32),
  `DELETE_FLAG` NUMERIC(1,0),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='航班信息子表-行李传送带表';

-- 航班信息子表-轮挡表
CREATE TABLE `DW_OPT_FLIGHT_CHOT` (
  `ID` BIGINT NOT NULL,
  `PID` BIGINT,
  `OPT_FS_AOBT` DATETIME(6),
  `OPT_FS_AIBT` DATETIME(6),
  `OPT_FS_DEPSTAND` VARCHAR(8),
  `OPT_FS_ARRSTAND` VARCHAR(8),
  `ODS_ID` BIGINT,
  `CREATED_TIME` TIMESTAMP(6),
  `UPDATED_TIME` TIMESTAMP(6),
  `CREATED_BY` VARCHAR(32),
  `UPDATED_BY` VARCHAR(32),
  `DELETE_FLAG` NUMERIC(1,0),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='航班信息子表-轮挡表';

-- 航班信息子表-值机柜台表
CREATE TABLE `DW_OPT_FLIGHT_CKDT` (
  `ID` BIGINT NOT NULL,
  `PID` BIGINT,
  `OPT_FS_CKNO` NUMERIC(2,0),
  `OPT_FS_CHECK_IN_DESK` VARCHAR(8),
  `OPT_FS_CCLS` VARCHAR(1),
  `OPT_FS_CHECKIN_OPEN_TIME` DATETIME(6),
  `OPT_FS_CHECKIN_CLOSE_TIME` DATETIME(6),
  `OPT_FS_COTM` DATETIME(6),
  `OPT_FS_CCTM` DATETIME(6),
  `OPT_FS_CTYP` VARCHAR(1),
  `ODS_ID` BIGINT,
  `CREATED_TIME` TIMESTAMP(6),
  `UPDATED_TIME` TIMESTAMP(6),
  `CREATED_BY` VARCHAR(32),
  `UPDATED_BY` VARCHAR(32),
  `DELETE_FLAG` NUMERIC(1,0),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='航班信息子表-值机柜台表';

-- 航班信息子表-航班延误表
CREATE TABLE `DW_OPT_FLIGHT_DELY` (
  `ID` BIGINT NOT NULL,
  `PID` BIGINT,
  `OPT_FS_DELAY` VARCHAR(3),
  `OPT_FS_STRT` DATETIME(6),
  `OPT_FS_DURA` VARCHAR(4),
  `OPT_FS_CONTENT` VARCHAR(160),
  `ODS_ID` BIGINT,
  `CREATED_TIME` TIMESTAMP(6),
  `UPDATED_TIME` TIMESTAMP(6),
  `CREATED_BY` VARCHAR(32),
  `UPDATED_BY` VARCHAR(32),
  `DELETE_FLAG` NUMERIC(1,0),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='航班信息子表-航班延误表';

-- 航班信息子表-航班航段表
CREATE TABLE `DW_OPT_FLIGHT_ERUT` (
  `ID` BIGINT NOT NULL,
  `PID` BIGINT,
  `OPT_FP_RTNO` NUMERIC(1,0),
  `OPT_FP_AP` VARCHAR(3),
  `OPT_FP_SIBT` DATETIME(6),
  `OPT_FP_SOBT` DATETIME(6),
  `ODS_ID` BIGINT,
  `CREATED_TIME` TIMESTAMP(6),
  `UPDATED_TIME` TIMESTAMP(6),
  `CREATED_BY` VARCHAR(32),
  `UPDATED_BY` VARCHAR(32),
  `DELETE_FLAG` NUMERIC(1,0),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='航班信息子表-航班航段表';

-- 航班信息子表-行李转盘表(东西区航显)
CREATE TABLE `DW_OPT_FLIGHT_FLBG` (
  `ID` BIGINT NOT NULL,
  `PID` BIGINT,
  `OPT_FP_BELT` VARCHAR(8),
  `OPT_FP_BCLS` VARCHAR(1),
  `OPT_FP_PCOT` DATETIME(6),
  `OPT_FP_PCCT` DATETIME(6),
  `OPT_FP_FBAG` DATETIME(6),
  `OPT_FP_LBAG` DATETIME(6),
  `OPT_FP_BTYP` VARCHAR(1),
  `ODS_ID` BIGINT,
  `CREATED_TIME` TIMESTAMP(6),
  `UPDATED_TIME` TIMESTAMP(6),
  `CREATED_BY` VARCHAR(32),
  `UPDATED_BY` VARCHAR(32),
  `DELETE_FLAG` NUMERIC(1,0),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='航班信息子表-行李转盘表(东西区航显)';

-- 航班信息子表-登机门表
CREATE TABLE `DW_OPT_FLIGHT_GTDT` (
  `ID` BIGINT NOT NULL,
  `PID` BIGINT,
  `OPT_FS_GTNO` NUMERIC(1,0),
  `OPT_FS_BOARDING_GATE` VARCHAR(8),
  `OPT_FS_ASBT` DATETIME(6),
  `OPT_FS_AEBT` DATETIME(6),
  `OPT_FS_GOTIME` DATETIME(6),
  `OPT_FS_GCTIME` DATETIME(6),
  `OPT_FS_GTYP` VARCHAR(1),
  `ODS_ID` BIGINT,
  `CREATED_TIME` TIMESTAMP(6),
  `UPDATED_TIME` TIMESTAMP(6),
  `CREATED_BY` VARCHAR(32),
  `UPDATED_BY` VARCHAR(32),
  `DELETE_FLAG` NUMERIC(1,0),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='航班信息子表-登机门表';

-- 执行其他DDL脚本
-- 这里可以添加其他表的创建语句

-- 确认初始化完成
SELECT 'Database initialization completed successfully!' AS message;